version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ark_admin
    ports:
      - "3306:3306"
    privileged: true
    restart: always
    command: ['--default-authentication-plugin=mysql_native_password']

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1